In [51]:
import pandas as pd
import os

In [2]:
import os

# Obtendo o nome do usu√°rio atual
username = os.getlogin()

print(username)

Markos Alves

In [3]:
caminho_arquivos = r"C:\Users\Markos Alves\Downloads\sales 2019".replace("\\","/")

for raiz, diretorios, arquivos in os.walk(caminho_arquivos):
    for arquivo in arquivos:
        print(arquivo)

Sales_April_2019.csv
Sales_August_2019.csv
Sales_December_2019.csv
Sales_February_2019.csv
Sales_January_2019.csv
Sales_July_2019.csv
Sales_June_2019.csv
Sales_March_2019.csv
Sales_May_2019.csv
Sales_November_2019.csv
Sales_October_2019.csv
Sales_September_2019.csv

In [4]:
#Transformando os arquivos em fata frames individuais e adicionando-os em uma lista
df_arq_cap = list()
for raiz, diretorios, arquivos in os.walk(caminho_arquivos):
    for arquivo in arquivos:
        caminho_completo = os.path.join(raiz, arquivo)
        df = pd.read_csv(caminho_completo)
        df_arq_cap.append(df)

In [5]:
for dataframe in df_arq_cap:
    display(dataframe.head(6))

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101"
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001"
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035"
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001"
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001"
5,236675,Wired Headphones,1,11.99,08/02/19 23:54,"470 Hill St, San Francisco, CA 94016"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700,12/30/19 00:01,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.0,12/29/19 07:03,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95,12/12/19 18:21,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99,12/22/19 15:13,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95,12/18/19 12:38,"43 Hill St, Atlanta, GA 30301"
5,295670,AA Batteries (4-pack),1,3.84,12/31/19 22:58,"200 Jefferson St, New York City, NY 10001"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,150502,iPhone,1,700,02/18/19 01:35,"866 Spruce St, Portland, ME 04101"
1,150503,AA Batteries (4-pack),1,3.84,02/13/19 07:24,"18 13th St, San Francisco, CA 94016"
2,150504,27in 4K Gaming Monitor,1,389.99,02/18/19 09:46,"52 6th St, New York City, NY 10001"
3,150505,Lightning Charging Cable,1,14.95,02/02/19 16:47,"129 Cherry St, Atlanta, GA 30301"
4,150506,AA Batteries (4-pack),2,3.84,02/28/19 20:32,"548 Lincoln St, Seattle, WA 98101"
5,150507,Lightning Charging Cable,1,14.95,02/24/19 18:50,"387 12th St, Austin, TX 73301"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,01/05/19 20:33,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"
5,141239,AAA Batteries (4-pack),1,2.99,01/29/19 20:22,"775 Willow St, San Francisco, CA 94016"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,222910,Apple Airpods Headphones,1,150,07/26/19 16:51,"389 South St, Atlanta, GA 30301"
1,222911,Flatscreen TV,1,300,07/05/19 08:55,"590 4th St, Seattle, WA 98101"
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301"
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301"
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101"
5,222915,Bose SoundSport Headphones,1,99.99,07/03/19 18:30,"899 Elm St, San Francisco, CA 94016"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,209921,USB-C Charging Cable,1,11.95,06/23/19 19:34,"950 Walnut St, Portland, ME 04101"
1,209922,Macbook Pro Laptop,1,1700.0,06/30/19 10:05,"80 4th St, San Francisco, CA 94016"
2,209923,ThinkPad Laptop,1,999.99,06/24/19 20:18,"402 Jackson St, Los Angeles, CA 90001"
3,209924,27in FHD Monitor,1,149.99,06/05/19 10:21,"560 10th St, Seattle, WA 98101"
4,209925,Bose SoundSport Headphones,1,99.99,06/25/19 18:58,"545 2nd St, San Francisco, CA 94016"
5,209926,Apple Airpods Headphones,1,150.0,06/28/19 20:04,"386 Lake St, Seattle, WA 98101"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,162009,iPhone,1,700,03/28/19 20:59,"942 Church St, Austin, TX 73301"
1,162009,Lightning Charging Cable,1,14.95,03/28/19 20:59,"942 Church St, Austin, TX 73301"
2,162009,Wired Headphones,2,11.99,03/28/19 20:59,"942 Church St, Austin, TX 73301"
3,162010,Bose SoundSport Headphones,1,99.99,03/17/19 05:39,"261 10th St, San Francisco, CA 94016"
4,162011,34in Ultrawide Monitor,1,379.99,03/10/19 00:01,"764 13th St, San Francisco, CA 94016"
5,162012,AA Batteries (4-pack),1,3.84,03/20/19 21:33,"187 Ridge St, San Francisco, CA 94016"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,194095,Wired Headphones,1,11.99,05/16/19 17:14,"669 2nd St, New York City, NY 10001"
1,194096,AA Batteries (4-pack),1,3.84,05/19/19 14:43,"844 Walnut St, Dallas, TX 75001"
2,194097,27in FHD Monitor,1,149.99,05/24/19 11:36,"164 Madison St, New York City, NY 10001"
3,194098,Wired Headphones,1,11.99,05/02/19 20:40,"622 Meadow St, Dallas, TX 75001"
4,194099,AAA Batteries (4-pack),2,2.99,05/11/19 22:55,"17 Church St, Seattle, WA 98101"
5,194100,iPhone,1,700.0,05/10/19 19:44,"81 Jefferson St, San Francisco, CA 94016"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,278797,Wired Headphones,1,11.99,11/21/19 09:54,"46 Park St, New York City, NY 10001"
1,278798,USB-C Charging Cable,2,11.95,11/17/19 10:03,"962 Hickory St, Austin, TX 73301"
2,278799,Apple Airpods Headphones,1,150.0,11/19/19 14:56,"464 Cherry St, Los Angeles, CA 90001"
3,278800,27in FHD Monitor,1,149.99,11/25/19 22:24,"649 10th St, Seattle, WA 98101"
4,278801,Bose SoundSport Headphones,1,99.99,11/09/19 13:56,"522 Hill St, Boston, MA 02215"
5,278802,USB-C Charging Cable,1,11.95,11/14/19 20:34,"154 2nd St, San Francisco, CA 94016"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,259358,34in Ultrawide Monitor,1,379.99,10/28/19 10:56,"609 Cherry St, Dallas, TX 75001"
1,259359,27in 4K Gaming Monitor,1,389.99,10/28/19 17:26,"225 5th St, Los Angeles, CA 90001"
2,259360,AAA Batteries (4-pack),2,2.99,10/24/19 17:20,"967 12th St, New York City, NY 10001"
3,259361,27in FHD Monitor,1,149.99,10/14/19 22:26,"628 Jefferson St, New York City, NY 10001"
4,259362,Wired Headphones,1,11.99,10/07/19 16:10,"534 14th St, Los Angeles, CA 90001"
5,259363,AAA Batteries (4-pack),1,2.99,10/01/19 18:55,"976 Lake St, New York City, NY 10001"

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,248151,AA Batteries (4-pack),4,3.84,09/17/19 14:44,"380 North St, Los Angeles, CA 90001"
1,248152,USB-C Charging Cable,2,11.95,09/29/19 10:19,"511 8th St, Austin, TX 73301"
2,248153,USB-C Charging Cable,1,11.95,09/16/19 17:48,"151 Johnson St, Los Angeles, CA 90001"
3,248154,27in FHD Monitor,1,149.99,09/27/19 07:52,"355 Hickory St, Seattle, WA 98101"
4,248155,USB-C Charging Cable,1,11.95,09/01/19 19:03,"125 5th St, Atlanta, GA 30301"
5,248156,34in Ultrawide Monitor,1,379.99,09/13/19 14:59,"469 12th St, Los Angeles, CA 90001"

In [6]:
for dataframe in df_arq_cap:
    print(dataframe.columns)
    print(dataframe.shape)

Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(18383, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(12011, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(25117, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(12036, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(9723, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(14371, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(13622, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(15226, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(16635, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(17661, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(20379, 6)
Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')
(11686, 6)

In [7]:
data_frame_vendas_2019 = pd.concat(df_arq_cap)

In [8]:
len(data_frame_vendas_2019['Product'].unique())

21

In [100]:
index_todrop = data_frame_vendas_2019[data_frame_vendas_2019['Price Each'] == 'Price Each'].index
index_todrop
data_frame_vendas_2019 = data_frame_vendas_2019.drop(index=index_todrop, axis=0)

In [101]:
data_frame_vendas_2019

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",19/04/2019 08:46
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",07/04/2019 22:30
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",30/04/2019 09:27
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",17/09/2019 20:56
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",01/09/2019 16:00
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",23/09/2019 07:39
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",19/09/2019 17:30
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",30/09/2019 00:18

In [10]:
import numpy as np

In [11]:
data_frame_vendas_2019[['data', 'hora']] = data_frame_vendas_2019['Order Date'].str.split(' ', expand=True)

In [12]:
data_frame_vendas_2019[['mes', 'dia', 'ano']] = data_frame_vendas_2019['data'].str.split('/', expand=True)

In [13]:
data_frame_vendas_2019['data'] = data_frame_vendas_2019['dia']+'/'+data_frame_vendas_2019['mes']+'/'+'20'+data_frame_vendas_2019['ano']+' '+data_frame_vendas_2019['hora']

In [14]:
data_frame_vendas_2019 = data_frame_vendas_2019.drop(columns=['hora', 'mes', 'dia', 'ano'])

In [15]:
data_frame_vendas_2019 = data_frame_vendas_2019.reset_index()
data_frame_vendas_2019 = data_frame_vendas_2019.drop(columns=['index'], axis=1)

In [16]:
data_frame_vendas_2019

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",19/04/2019 08:46
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",07/04/2019 22:30
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",17/09/2019 20:56
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",01/09/2019 16:00
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",23/09/2019 07:39
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",19/09/2019 17:30
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",30/09/2019 00:18

In [17]:
index_to_drop = data_frame_vendas_2019[data_frame_vendas_2019['Order ID'].isnull()].index

In [18]:
index_to_drop

Int64Index([     1,    356,    735,   1433,   1553,   1571,   1992,   2265,
              2798,   3024,
            ...
            184408, 184546, 184836, 185017, 185100, 185176, 185438, 186042,
            186548, 186826],
           dtype='int64', length=545)

In [19]:
data_frame_vendas_2019 = data_frame_vendas_2019.drop(index=index_to_drop)

In [20]:
data_frame_vendas_2019

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",19/04/2019 08:46
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",07/04/2019 22:30
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",30/04/2019 09:27
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",17/09/2019 20:56
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",01/09/2019 16:00
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",23/09/2019 07:39
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",19/09/2019 17:30
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",30/09/2019 00:18

# Estudo de regras da associa√ß√£o

In [21]:
orders_ids = data_frame_vendas_2019['Order ID'].unique()
combinacoes = list()

In [ ]:
# for order_id in orders_ids:
#     combinacao = data_frame_vendas_2019[data_frame_vendas_2019['Order ID'] == order_id]
#     combinacao = combinacao['Product'].unique()
#     combinacoes.append(combinacao)

In [ ]:
# combinacoes

In [ ]:
# tam = 0
# for combinacao in combinacoes:
#     if len(combinacao) > tam:
#         tam = len(combinacao)
# print(tam)

In [ ]:
# finals = list()
# for combinacao in combinacoes:
#     combinacao = list(combinacao)
    
#     if len(combinacao) == 1:
#         combinacao.append(0)
#         combinacao.append(0)
#         combinacao.append(0)
#         combinacao.append(0)
#         finals.append(combinacao)
        
#     elif len(combinacao) == 2:
#         combinacao.append(0)
#         combinacao.append(0)
#         combinacao.append(0)
#         finals.append(combinacao)
        
#     elif len(combinacao) == 3:
#         combinacao.append(0)
#         combinacao.append(0)
#         finals.append(combinacao)
        
#     elif len(combinacao) == 4:
#         combinacao.append(0)
#         finals.append(combinacao)
        
#     else:
#         finals.append(combinacao)

In [ ]:
# Regras = pd.DataFrame({
#     'Order ID': orders_ids,
#     'Cesta': finals
# })

In [ ]:
# Regras['Cesta'] = Regras['Cesta'].astype(str)
# Regras['Cesta'] = Regras['Cesta'].str.replace(r"'","")
# Regras['Cesta'] = Regras['Cesta'].str.replace(r"[","")
# Regras['Cesta'] = Regras['Cesta'].str.replace(r"]","")
# Regras[['A', 'B', 'C', 'D', 'E']] = Regras['Cesta'].str.split(",",expand=True)
# Regras['Cesta'] = Regras['Cesta'].str.replace(",",".")

# Regras['A'] = Regras['A'].astype(str)
# Regras['B'] = Regras['B'].astype(str) 
# Regras['C'] = Regras['C'].astype(str)
# Regras['D'] = Regras['D'].astype(str)
# Regras['E'] = Regras['E'].astype(str)

# Regras['A'] = Regras['A'].str.replace('0', '')
# Regras['B'] = Regras['B'].str.replace('0', '')
# Regras['C'] = Regras['C'].str.replace('0', '')
# Regras['D'] = Regras['D'].str.replace('0', '')
# Regras['E'] = Regras['E'].str.replace('0', '')

In [ ]:
# Regras.dtypes

In [ ]:
# Regras

In [ ]:
# Regras.isnull().sum()

In [ ]:
# for regra in Regras['Cesta']:
#     print(regra)

# Regras de associa√ß√£o

In [ ]:
# caminho = r"C:\Users\Markos Alves\Downloads\regras.csv".replace("\\","/")

In [ ]:
# Regras.to_csv(caminho, sep=',', index=False)

In [ ]:
# regras_to_analise = pd.read_csv(caminho)

In [ ]:
# regras_to_analise

In [ ]:
# regras_de_analise = regras_to_analise[['A', 'B', 'C', 'D', 'E']]

In [ ]:
# regras_de_analise

In [ ]:
# transacoes = list()
# for i in range(regras_de_analise.shape[0]):
#   #print(i)
#   transacoes.append([str(regras_de_analise.values[i, j]) for j in range(regras_de_analise.shape[1])])

In [ ]:
# transacoes

# Estudo final

In [22]:
assiacoes = r"C:\Users\Markos Alves\Downloads\C__Users_Markos Alves_Downloads_associacoes.csv".replace("\\","/")

In [23]:
regras = pd.read_csv(assiacoes)
regras = regras.drop(columns=['Unnamed: 0'])
regras

,SE,ENTAO,SUPPORTE,CONFIANCA,LIFT
0,Apple Airpods Headphones,iPhone,0.002099,0.620000,16.235792
1,iPhone,Apple Airpods Headphones,0.002099,0.054965,16.235792
2,Bose SoundSport Headphones,Google Phone,0.001151,0.401575,13.016076
3,Google Phone,Bose SoundSport Headphones,0.001151,0.037308,13.016076
4,Lightning Charging Cable,iPhone,0.005529,0.733533,19.208852
5,iPhone,Lightning Charging Cable,0.005529,0.144799,19.208852
6,USB-C Charging Cable,Google Phone,0.005597,0.594724,19.276548
7,Google Phone,USB-C Charging Cable,0.005597,0.181419,19.276548
8,USB-C Charging Cable,Vareebadd Phone,0.001941,0.206235,17.847385
9,Vareebadd Phone,USB-C Charging Cable,0.001941,0.167969,17.847385
10,Wired Headphones,Google Phone,0.002167,0.305732,9.909579
11,Google Phone,Wired Headphones,0.002167,0.070227,9.909579
12,Wired Headphones,iPhone,0.002505,0.353503,9.257103
13,iPhone,Wired Headphones,0.002505,0.065603,9.257103
14,Apple Airpods Headphones,iPhone,0.002099,0.620000,16.235792
15,iPhone,Apple Airpods Headphones,0.002099,0.054965,16.235792
16,Apple Airpods Headphones,iPhone,0.002099,0.620000,16.235792
17,iPhone,Apple Airpods Headphones,0.002099,0.054965,16.235792
18,Bose SoundSport Headphones,Google Phone,0.001151,0.401575,13.016076
19,Google Phone,Bose SoundSport Headphones,0.001151,0.037308,13.016076
20,Bose SoundSport Headphones,Google Phone,0.001151,0.401575,13.016076
21,Google Phone,Bose SoundSport Headphones,0.001151,0.037308,13.016076
22,Lightning Charging Cable,iPhone,0.005529,0.733533,19.208852
23,iPhone,Lightning Charging Cable,0.005529,0.144799,19.208852
24,Lightning Charging Cable,iPhone,0.005529,0.733533,19.208852
25,iPhone,Lightning Charging Cable,0.005529,0.144799,19.208852
26,USB-C Charging Cable,Google Phone,0.005597,0.594724,19.276548
27,Google Phone,USB-C Charging Cable,0.005597,0.181419,19.276548
28,USB-C Charging Cable,Google Phone,0.005597,0.594724,19.276548
29,Google Phone,USB-C Charging Cable,0.005597,0.181419,19.276548
30,USB-C Charging Cable,Vareebadd Phone,0.001941,0.206235,17.847385
31,Vareebadd Phone,USB-C Charging Cable,0.001941,0.167969,17.847385
32,USB-C Charging Cable,Vareebadd Phone,0.001941,0.206235,17.847385
33,Vareebadd Phone,USB-C Charging Cable,0.001941,0.167969,17.847385
34,Wired Headphones,Google Phone,0.002167,0.305732,9.909579
35,Google Phone,Wired Headphones,0.002167,0.070227,9.909579
36,Wired Headphones,Google Phone,0.002167,0.305732,9.909579
37,Google Phone,Wired Headphones,0.002167,0.070227,9.909579
38,Wired Headphones,iPhone,0.002505,0.353503,9.257103
39,iPhone,Wired Headphones,0.002505,0.065603,9.257103
40,Wired Headphones,iPhone,0.002505,0.353503,9.257103
41,iPhone,Wired Headphones,0.002505,0.065603,9.257103

In [24]:
data_frame_vendas_2019

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",19/04/2019 08:46
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",07/04/2019 22:30
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",30/04/2019 09:27
...,...,...,...,...,...,...,...
186845,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001",17/09/2019 20:56
186846,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016",01/09/2019 16:00
186847,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016",23/09/2019 07:39
186848,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016",19/09/2019 17:30
186849,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016",30/09/2019 00:18

In [25]:
data_frame_vendas_2019.shape[0]

186305

* ver o n√∫mero de compras que possuem mais de um elemento
* ver o n√∫mero de compras solteira
* ver qual a distribui√ß√£o das combina√ß√µes

In [ ]:
# dfs = list()
# for o_id in orders_ids:
#     new_df = data_frame_vendas_2019[data_frame_vendas_2019['Order ID'] == o_id]
#     if new_df.shape[0] == 1:
#         dfs.append(new_df)

In [ ]:
# dfs_combinations = pd.concat(dfs)
# dfs_combinations.to_csv(r"C:\Users\Markos Alves\Downloads\comprasunicas.csv".replace("\\","/"))

In [ ]:
# dfs = list()
# for o_id in orders_ids:
#     new_df = data_frame_vendas_2019[data_frame_vendas_2019['Order ID'] == o_id]
#     if new_df.shape[0] > 1:
#         dfs.append(new_df)

In [27]:
# dfs_combinations = pd.concat(dfs)
# dfs_combinations.to_csv(r"C:\Users\Markos Alves\Downloads\multiplascompras.csv".replace("\\","/"))

In [28]:
dfs_combinations = pd.read_csv(r"C:\Users\Markos Alves\Downloads\multiplascompras.csv".replace("\\","/"))
dfs_combinations = dfs_combinations.drop(columns=['Unnamed: 0'])

dfs_combinations[['data', 'hora']] = dfs_combinations['Order Date'].str.split(' ', expand=True)
dfs_combinations[['mes', 'dia', 'ano']] = dfs_combinations['data'].str.split('/', expand=True)
dfs_combinations['data'] = dfs_combinations['dia']+'/'+dfs_combinations['mes']+'/'+'20'+dfs_combinations['ano']+' '+dfs_combinations['hora']
dfs_combinations = dfs_combinations.drop(columns=['hora', 'mes', 'dia', 'ano'])
dfs_combinations = dfs_combinations.reset_index()
dfs_combinations = dfs_combinations.drop(columns=['index'], axis=1)

dfs_combinations.to_csv(r"C:\Users\Markos Alves\Downloads\multiplascompras.csv".replace("\\","/"))

dfs_combinations

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
1,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",12/04/2019 14:38
2,176574,Google Phone,1,600,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",03/04/2019 19:42
3,176574,USB-C Charging Cable,1,11.95,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001",03/04/2019 19:42
4,176585,Bose SoundSport Headphones,1,99.99,04/07/19 11:31,"823 Highland St, Boston, MA 02215",07/04/2019 11:31
...,...,...,...,...,...,...,...
14999,259303,AA Batteries (4-pack),1,3.84,09/20/19 20:18,"106 7th St, Atlanta, GA 30301",20/09/2019 20:18
15000,259314,Wired Headphones,1,11.99,09/16/19 00:25,"241 Highland St, Atlanta, GA 30301",16/09/2019 00:25
15001,259314,AAA Batteries (4-pack),2,2.99,09/16/19 00:25,"241 Highland St, Atlanta, GA 30301",16/09/2019 00:25
15002,259350,Google Phone,1,600,09/30/19 13:49,"519 Maple St, San Francisco, CA 94016",30/09/2019 13:49
15003,259350,USB-C Charging Cable,1,11.95,09/30/19 13:49,"519 Maple St, San Francisco, CA 94016",30/09/2019 13:49

In [105]:
data_frame_vendas_2019['Price Each'] = data_frame_vendas_2019['Price Each'].astype(float)
data_frame_vendas_2019['Quantity Ordered'] = data_frame_vendas_2019['Quantity Ordered'].astype(float)

In [109]:
data_frame_vendas_2019.dtypes

Order ID             object
Product              object
Quantity Ordered    float64
Price Each          float64
Order Date           object
Purchase Address     object
data                 object
dtype: object

In [29]:
products = dfs_combinations['Product'].unique()
print(len(products))
print(products)

20
['Google Phone' 'Wired Headphones' 'USB-C Charging Cable'
 'Bose SoundSport Headphones' 'AAA Batteries (4-pack)'
 'Lightning Charging Cable' 'Apple Airpods Headphones' 'ThinkPad Laptop'
 '34in Ultrawide Monitor' 'iPhone' '27in FHD Monitor' 'Product'
 '27in 4K Gaming Monitor' 'Macbook Pro Laptop' 'AA Batteries (4-pack)'
 'Flatscreen TV' 'Vareebadd Phone' '20in Monitor' 'LG Dryer'
 'LG Washing Machine']

In [30]:
for order_id in dfs_combinations['Order ID'].unique():
    combinacao = data_frame_vendas_2019[data_frame_vendas_2019['Order ID'] == order_id]
    combinacao = combinacao['Product'].unique()
    combinacoes.append(combinacao)
combinacoes

[array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Bose SoundSport Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Google Phone'], dtype=object),
 array(['Lightning Charging Cable', 'USB-C Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'ThinkPad Laptop'], dtype=object),
 array(['Bose SoundSport Headphones', 'AAA Batteries (4-pack)'],
       dtype=object),
 array(['34in Ultrawide Monitor', 'Google Phone'], dtype=object),
 array(['Lightning Charging Cable', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'Bose SoundSport Headphones', 'Wired Headphones'],
       dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)', '27in FHD Monitor'], dtype=object),
 array(['USB-C Charging Cable', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['Product'], dtype=object),
 array(['iPhone', '27in 4K Gaming Monitor'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['ThinkPad Laptop', 'AAA Batteries (4-pack)'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones', 'AAA Batteries (4-pack)'],
       dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'Apple Airpods Headphones'], dtype=object),
 array(['Macbook Pro Laptop', 'ThinkPad Laptop'], dtype=object),
 array(['AA Batteries (4-pack)', 'Flatscreen TV'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['USB-C Charging Cable', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'AA Batteries (4-pack)'], dtype=object),
 array(['AA Batteries (4-pack)', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Bose SoundSport Headphones', 'AA Batteries (4-pack)'],
       dtype=object),
 array(['20in Monitor', 'Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable',
        'Bose SoundSport Headphones'], dtype=object),
 array(['27in FHD Monitor', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', '27in 4K Gaming Monitor'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['ThinkPad Laptop', 'Google Phone'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'Google Phone'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Bose SoundSport Headphones', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'Google Phone'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Macbook Pro Laptop'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['USB-C Charging Cable', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['Lightning Charging Cable', '27in 4K Gaming Monitor'], dtype=object),
 array(['Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable', 'Wired Headphones'],
       dtype=object),
 array(['Apple Airpods Headphones', 'Lightning Charging Cable'],
       dtype=object),
 array(['AA Batteries (4-pack)', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['34in Ultrawide Monitor', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Lightning Charging Cable', 'AA Batteries (4-pack)'], dtype=object),
 array(['Lightning Charging Cable', 'AA Batteries (4-pack)'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable', 'Wired Headphones'],
       dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['AA Batteries (4-pack)', 'Macbook Pro Laptop'], dtype=object),
 array(['Vareebadd Phone', 'Wired Headphones'], dtype=object),
 array(['Flatscreen TV', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'ThinkPad Laptop'], dtype=object),
 array(['Bose SoundSport Headphones', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'Wired Headphones'], dtype=object),
 array(['Bose SoundSport Headphones', 'USB-C Charging Cable'], dtype=object),
 array(['USB-C Charging Cable', '20in Monitor'], dtype=object),
 array(['AAA Batteries (4-pack)', 'AA Batteries (4-pack)'], dtype=object),
 array(['AA Batteries (4-pack)', 'Bose SoundSport Headphones'],
       dtype=object),
 array(['USB-C Charging Cable', '27in 4K Gaming Monitor'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['27in 4K Gaming Monitor', 'Bose SoundSport Headphones'],
       dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Lightning Charging Cable', 'AAA Batteries (4-pack)'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['34in Ultrawide Monitor', 'Macbook Pro Laptop'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'USB-C Charging Cable'], dtype=object),
 array(['Wired Headphones', 'AA Batteries (4-pack)'], dtype=object),
 array(['Macbook Pro Laptop', 'Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['USB-C Charging Cable', 'AA Batteries (4-pack)'], dtype=object),
 array(['Google Phone', 'Bose SoundSport Headphones'], dtype=object),
 array(['Macbook Pro Laptop', '20in Monitor'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'Bose SoundSport Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'Flatscreen TV'], dtype=object),
 array(['AA Batteries (4-pack)', 'Flatscreen TV'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['USB-C Charging Cable', '27in FHD Monitor'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['20in Monitor', 'Bose SoundSport Headphones'], dtype=object),
 array(['Flatscreen TV', 'AA Batteries (4-pack)'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Bose SoundSport Headphones', 'AA Batteries (4-pack)'],
       dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['USB-C Charging Cable', 'ThinkPad Laptop'], dtype=object),
 array(['Apple Airpods Headphones'], dtype=object),
 array(['27in FHD Monitor', 'AAA Batteries (4-pack)'], dtype=object),
 array(['USB-C Charging Cable', 'Bose SoundSport Headphones'], dtype=object),
 array(['iPhone', 'AAA Batteries (4-pack)'], dtype=object),
 array(['USB-C Charging Cable', 'iPhone'], dtype=object),
 array(['AA Batteries (4-pack)', 'Wired Headphones'], dtype=object),
 array(['27in FHD Monitor', 'AA Batteries (4-pack)'], dtype=object),
 array(['Lightning Charging Cable', 'Google Phone'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['AA Batteries (4-pack)', 'AAA Batteries (4-pack)'], dtype=object),
 array(['AA Batteries (4-pack)', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Bose SoundSport Headphones', 'Lightning Charging Cable'],
       dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['Apple Airpods Headphones', 'USB-C Charging Cable'], dtype=object),
 array(['Wired Headphones', 'iPhone'], dtype=object),
 array(['27in 4K Gaming Monitor', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['27in 4K Gaming Monitor', 'Vareebadd Phone'], dtype=object),
 array(['Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['AA Batteries (4-pack)', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'AA Batteries (4-pack)'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Wired Headphones', 'Apple Airpods Headphones'], dtype=object),
 array(['Apple Airpods Headphones', '27in FHD Monitor'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable',
        'Bose SoundSport Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)'], dtype=object),
 array(['AAA Batteries (4-pack)', '27in 4K Gaming Monitor'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Bose SoundSport Headphones', 'AA Batteries (4-pack)'],
       dtype=object),
 array(['Google Phone', 'Bose SoundSport Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable', 'Wired Headphones'],
       dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Lightning Charging Cable', 'LG Dryer'], dtype=object),
 array(['Apple Airpods Headphones', 'Bose SoundSport Headphones'],
       dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Google Phone'], dtype=object),
 array(['Macbook Pro Laptop', '34in Ultrawide Monitor'], dtype=object),
 array(['Flatscreen TV'], dtype=object),
 array(['AA Batteries (4-pack)', 'USB-C Charging Cable'], dtype=object),
 array(['20in Monitor', 'Bose SoundSport Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable', 'Vareebadd Phone'],
       dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'Wired Headphones'], dtype=object),
 array(['27in 4K Gaming Monitor', 'Apple Airpods Headphones'], dtype=object),
 array(['Wired Headphones'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Google Phone'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['27in FHD Monitor', 'AAA Batteries (4-pack)'], dtype=object),
 array(['AAA Batteries (4-pack)', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['AA Batteries (4-pack)', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', '34in Ultrawide Monitor'], dtype=object),
 array(['AAA Batteries (4-pack)', 'AA Batteries (4-pack)'], dtype=object),
 array(['Vareebadd Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Bose SoundSport Headphones'],
       dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'Wired Headphones'], dtype=object),
 array(['Bose SoundSport Headphones', 'AAA Batteries (4-pack)'],
       dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Wired Headphones', 'Lightning Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'Bose SoundSport Headphones'], dtype=object),
 array(['AA Batteries (4-pack)', 'Apple Airpods Headphones'], dtype=object),
 array(['34in Ultrawide Monitor', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['AAA Batteries (4-pack)'], dtype=object),
 array(['AAA Batteries (4-pack)', '27in FHD Monitor'], dtype=object),
 array(['Bose SoundSport Headphones', 'AAA Batteries (4-pack)'],
       dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Lightning Charging Cable', 'AAA Batteries (4-pack)'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['20in Monitor', 'Lightning Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Bose SoundSport Headphones', 'ThinkPad Laptop'], dtype=object),
 array(['AA Batteries (4-pack)', 'Apple Airpods Headphones'], dtype=object),
 array(['USB-C Charging Cable', 'AA Batteries (4-pack)'], dtype=object),
 array(['27in FHD Monitor', 'Bose SoundSport Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['AA Batteries (4-pack)', 'Apple Airpods Headphones'], dtype=object),
 array(['AA Batteries (4-pack)', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['Apple Airpods Headphones', 'AAA Batteries (4-pack)'], dtype=object),
 array(['AA Batteries (4-pack)', 'Lightning Charging Cable'], dtype=object),
 array(['AA Batteries (4-pack)', 'Apple Airpods Headphones'], dtype=object),
 array(['20in Monitor', 'Macbook Pro Laptop'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['iPhone', 'Wired Headphones'], dtype=object),
 array(['AAA Batteries (4-pack)', 'Wired Headphones'], dtype=object),
 array(['Bose SoundSport Headphones', '27in FHD Monitor'], dtype=object),
 array(['Apple Airpods Headphones', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Macbook Pro Laptop', 'AA Batteries (4-pack)'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['AA Batteries (4-pack)', 'Lightning Charging Cable'], dtype=object),
 array(['27in 4K Gaming Monitor', 'Bose SoundSport Headphones'],
       dtype=object),
 array(['USB-C Charging Cable', 'AAA Batteries (4-pack)'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Lightning Charging Cable'], dtype=object),
 array(['Lightning Charging Cable', 'Google Phone'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable', 'Wired Headphones'],
       dtype=object),
 array(['iPhone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable', 'Wired Headphones'],
       dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['ThinkPad Laptop', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'ThinkPad Laptop'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', '27in 4K Gaming Monitor'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['USB-C Charging Cable', 'Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'AA Batteries (4-pack)'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Google Phone', 'Bose SoundSport Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable', 'Apple Airpods Headphones'],
       dtype=object),
 array(['iPhone', '34in Ultrawide Monitor'], dtype=object),
 array(['Google Phone', 'Wired Headphones'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable', 'Wired Headphones'],
       dtype=object),
 array(['20in Monitor', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Apple Airpods Headphones'], dtype=object),
 array(['Google Phone', 'USB-C Charging Cable'], dtype=object),
 array(['Vareebadd Phone', 'USB-C Charging Cable'], dtype=object),
 array(['iPhone', 'Lightning Charging Cable'], dtype=object),
 array(['Apple Airpods Headphones', 'AAA Batteries (4-pack)'], dtype=object),
 array(['AAA Batteries (4-pack)', '27in FHD Monitor'], dtype=object),
 array(['USB-C Charging Cable', 'AA Batteries (4-pack)'], dtype=object),

In [123]:
#Data frame com o numedo de vezes que os produtos foram vendidos
data_frame_vendas_counts = data_frame_vendas_2019[data_frame_vendas_2019['Product'].isin(products)]
data_frame_vendas_counts = data_frame_vendas_counts.groupby(['Product']).count()
data_frame_vendas_counts = data_frame_vendas_counts.reset_index()

In [124]:
data_frame_vendas_cm = data_frame_vendas_2019[data_frame_vendas_2019['Product'].isin(products)]
data_frame_vendas_cm = data_frame_vendas_cm.groupby(['Product']).mean()
data_frame_vendas_cm = data_frame_vendas_cm.reset_index()

C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_28140\3679886241.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data_frame_vendas_cm = data_frame_vendas_cm.groupby(['Product']).mean()

In [125]:
# Numero de vezes que os produtos foram comprados isolados
compras_unicas = r"C:\Users\Markos Alves\Downloads\comprasunicas.csv".replace("\\","/")

compras_unicas = pd.read_csv(compras_unicas)
compras_unicas = compras_unicas[compras_unicas['Product'].isin(products)]
compras_unicas = compras_unicas.groupby(['Product']).count()
compras_unicas = compras_unicas.reset_index()

In [130]:
# Numero de vezes que os produtos foram comprados combinado
compras_multiplas = r"C:\Users\Markos Alves\Downloads\multiplascompras.csv".replace("\\","/")

compras_multiplas = pd.read_csv(compras_multiplas)
compras_multiplas = compras_multiplas[(compras_multiplas['Product'].isin(products)) & (compras_multiplas['Product'] != 'Product') ]
compras_multiplas = compras_multiplas.groupby(['Product']).count()
compras_multiplas = compras_multiplas.reset_index()

In [131]:
display(data_frame_vendas_counts.head(5))
display(data_frame_vendas_cm.head(5))
display(compras_unicas.head(5))
display(compras_multiplas.head(5))

,Product,Order ID,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,20in Monitor,4101,4101,4101,4101,4101,4101
1,27in 4K Gaming Monitor,6230,6230,6230,6230,6230,6230
2,27in FHD Monitor,7507,7507,7507,7507,7507,7507
3,34in Ultrawide Monitor,6181,6181,6181,6181,6181,6181
4,AA Batteries (4-pack),20577,20577,20577,20577,20577,20577

                  Product  Quantity Ordered  Price Each
0            20in Monitor          1.006828  109.989998
1  27in 4K Gaming Monitor          1.002247  389.989990
2        27in FHD Monitor          1.005728  149.990005
3  34in Ultrawide Monitor          1.002912  379.989990
4   AA Batteries (4-pack)          1.343004    3.840000

,Product,Unnamed: 0,Order ID,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,20in Monitor,3942,3942,3942,3942,3942,3942,3942
1,27in 4K Gaming Monitor,5979,5979,5979,5979,5979,5979,5979
2,27in FHD Monitor,7213,7213,7213,7213,7213,7213,7213
3,34in Ultrawide Monitor,5935,5935,5935,5935,5935,5935,5935
4,AA Batteries (4-pack),19809,19809,19809,19809,19809,19809,19809

,Product,Unnamed: 0,Order ID,Quantity Ordered,Price Each,Order Date,Purchase Address,data
0,20in Monitor,159,159,159,159,159,159,159
1,27in 4K Gaming Monitor,251,251,251,251,251,251,251
2,27in FHD Monitor,294,294,294,294,294,294,294
3,34in Ultrawide Monitor,246,246,246,246,246,246,246
4,AA Batteries (4-pack),768,768,768,768,768,768,768

In [132]:
final_data_frame = pd.DataFrame({
    "produto vendas":data_frame_vendas_counts['Product'],
    "N de vendas": data_frame_vendas_counts['Order ID'],
    "produto unicos": compras_unicas['Product'],
    "Vendas unicas": compras_unicas['Order ID'],
    "produto multiplos": compras_multiplas['Product'],
    "vendas multiplas": compras_multiplas['Order ID'],
    "Produto medio": data_frame_vendas_cm['Product'],
    "Valor medio": data_frame_vendas_cm["Price Each"]
})

In [133]:
final_data_frame

,produto vendas,N de vendas,produto unicos,Vendas unicas,produto multiplos,vendas multiplas,Produto medio,Valor medio
0,20in Monitor,4101,20in Monitor,3942,20in Monitor,159,20in Monitor,109.989998
1,27in 4K Gaming Monitor,6230,27in 4K Gaming Monitor,5979,27in 4K Gaming Monitor,251,27in 4K Gaming Monitor,389.989990
2,27in FHD Monitor,7507,27in FHD Monitor,7213,27in FHD Monitor,294,27in FHD Monitor,149.990005
3,34in Ultrawide Monitor,6181,34in Ultrawide Monitor,5935,34in Ultrawide Monitor,246,34in Ultrawide Monitor,379.989990
4,AA Batteries (4-pack),20577,AA Batteries (4-pack),19809,AA Batteries (4-pack),768,AA Batteries (4-pack),3.840000
5,AAA Batteries (4-pack),20641,AAA Batteries (4-pack),19826,AAA Batteries (4-pack),815,AAA Batteries (4-pack),2.990000
6,Apple Airpods Headphones,15549,Apple Airpods Headphones,14575,Apple Airpods Headphones,974,Apple Airpods Headphones,150.000000
7,Bose SoundSport Headphones,13325,Bose SoundSport Headphones,12505,Bose SoundSport Headphones,820,Bose SoundSport Headphones,99.989998
8,Flatscreen TV,4800,Flatscreen TV,4622,Flatscreen TV,178,Flatscreen TV,300.000000
9,Google Phone,5525,Google Phone,3886,Google Phone,1639,Google Phone,600.000000
10,LG Dryer,646,LG Dryer,621,LG Dryer,25,LG Dryer,600.000000
11,LG Washing Machine,666,LG Washing Machine,638,LG Washing Machine,28,LG Washing Machine,600.000000
12,Lightning Charging Cable,21658,Lightning Charging Cable,19831,Lightning Charging Cable,1827,Lightning Charging Cable,14.950000
13,Macbook Pro Laptop,4724,Macbook Pro Laptop,4528,Macbook Pro Laptop,196,Macbook Pro Laptop,1700.000000
14,ThinkPad Laptop,4128,ThinkPad Laptop,3952,ThinkPad Laptop,176,ThinkPad Laptop,999.989990
15,USB-C Charging Cable,21903,USB-C Charging Cable,19792,USB-C Charging Cable,2111,USB-C Charging Cable,11.950000
16,Vareebadd Phone,2065,Vareebadd Phone,1464,Vareebadd Phone,601,Vareebadd Phone,400.000000
17,Wired Headphones,18882,Wired Headphones,17208,Wired Headphones,1674,Wired Headphones,11.990000
18,iPhone,6842,iPhone,4975,iPhone,1867,iPhone,700.000000

In [134]:
final_data_frame.to_csv(r"C:\Users\Markos Alves\Downloads\finalanalise.csv".replace("\\","/"), index = False)

In [ ]:
# def converte_data(data=pd.Series(), formato_atual='dd-mm-yyyy', formato_final='dd/mm/yyyy', horas=False):
#     datas = np.array(data)
#     datas = data.astype('object')
#     datas = data.str.strip()
#     if formato_atual == 'dd-mm-yyyy' and horas ==  False:
#         if formato_final == 'dd/mm/yyyy':
#             datas = datas.str.split('-', expand=True)