In [1]:
import pandas as pd

In [2]:
caminho_excelencia = r"C:\Users\Markos Alves\Downloads\terceirizadas horiginal\Excelencia.xlsx".replace("\\","/")
caminho_ranking  = r"C:\Users\Markos Alves\Downloads\terceirizadas horiginal\Ranking.xlsx".replace("\\","/")
caminho_marlin = r"C:\Users\Markos Alves\Downloads\terceirizadas horiginal\Marlin.xlsx".replace("\\","/")
caminho_DPG = r"C:\Users\Markos Alves\Downloads\terceirizadas horiginal\DPG.xlsx".replace("\\","/")

In [3]:
#### Adicionando coluna padrão em 'Excelencia'
df_excelencia = pd.read_excel(caminho_excelencia)
df_excelencia = df_excelencia.assign(profit='Excelencia')

#### Adicionando coluna padrão em 'DPG'
df_DPG = pd.read_excel(caminho_DPG)
df_DPG = df_DPG.assign(profit='DPG')

#### Adicionando coluna padrão em 'Ranking'
df_ranking = pd.read_excel(caminho_ranking)
df_ranking = df_ranking.assign(profit='Ranking')

#### Adicionando coluna padrão em 'Ranking'
df_Marlin = pd.read_excel(caminho_marlin)
df_Marlin = df_Marlin.assign(profit='Marlin')

In [4]:
display(df_DPG.head(3))
display(df_excelencia.head(3))
display(df_Marlin.head(3))
display(df_ranking.head(3))

,ST,C. CUSTO,DATA,HORA,ORIGEM,DESTINO,VALOR TOTAL,SOLICITANTE,PASSAGEIRO,PLACA,MOTORISTA,TIPO,profit
0,511878/511570/511857/511868/511862,110402/110846/110086/110086/110846/110888,2022-05-16,06:30:00,CARAVELAS,FABRICA,330.0,EMMANUEL SILVA DE ANDRADE,EMMANUEL SILVA DE ANDRADE,ETIOS,CRISTOGENES,CHAMADA,DPG
1,512162/512131/512206,110085/110086/110096,2022-06-09,18:00:00,CONCEIÇÃO DA BARRA COCB,TEIXEIRA DE FREITAS,460.0,FERNANDA FERREIRA CONTARDI,FERNANDA FERREIRA CONTARDI,ETIOS,CRISTOGENES,CHAMADA,DPG
2,E-MAIL,110065,2022-06-10,18:00:00,CONCEIÇÃO DA BARRA COCB,TEIXEIRA DE FREITAS,460.0,FERNANDA FERREIRA CONTARDI,FERNANDA FERREIRA CONTARDI,ETIOS,CRISTOGENES,CHAMADA,DPG

,ST,C. CUSTO,DATA,HORA,ORIGEM,DESTINO,VALOR TOTAL,SOLICITANTE,PASSAGEIRO,PLACA,MOTORISTA,TIPO,profit
0,512751,110096,2022-01-06 00:00:00,02:00:00,FABRICA,POSTO DA MATA,134.89,JAILDO BATISTA,JAILDO BATISTA,QRC-5741,FABIO SHIRLEI,CHAMADA,Excelencia
1,512760,110579,2022-01-06 00:00:00,04:00:00,FABRICA,MUCURI,161.48,ALDENIR COSTA NERES,VANILDO DOS SANTOS/ FABIANO BORGES,QRC-5741,FABIO SHIRLEI,CHAMADA,Excelencia
2,511557,110420,2022-01-06 00:00:00,06:00:00,MUCURI,FABRICA,161.48,FABIO LOZER MATTOS,FABIO LOZER MATTOS,QRC-5741,FABIO SHIRLEI,CHAMADA,Excelencia

,ST,C. CUSTO,DATA,HORA,ORIGEM,DESTINO,VALOR TOTAL,SOLICITANTE,PASSAGEIRO,PLACA,MOTORISTA,TIPO,profit
0,523803,03BCCCI002,2022-02-01,08:30:00,C. ITAPEM,ITABATÃ,1347.8,RONIEL / FABRÍCIO / ALEF,RONIEL / FABRÍCIO / ALEF,NaN,VINICIUS,CHAMADA,Marlin
1,524722,110389,2022-02-06,14:00:00,V. VELHA,MUCURI,1043.8,RICARDO BARROS DE OLIVEIRA,RICARDO BARROS DE OLIVEIRA,NaN,VINICIUS,CHAMADA,Marlin
2,526882,101543,2022-02-09,09:30:00,VITÓRIA/ES,POUS.RIO MUC,910.2,MAYARA SILVA OLIVEIRA,MAYARA SILVA OLIVEIRA,NaN,VINICIUS,CHAMADA,Marlin

,ST,C. CUSTO,DATA,HORA,ORIGEM,DESTINO,VALOR TOTAL,SOLICITANTE,PASSAGEIRO,PLACA,MOTORISTA,TIPO,profit
0,512150,110368,2022-01-05,13:00:00,MUCURI,VITORIA AEROPORTO,1080.880,LEDA MARIA,BERNARDO CAUX,RQS0B74,SERGIO,CHAMADA,Ranking
1,512314,110061,2022-01-05,02:00:00,FABRICA,ITABATAN,32.812,JOSIANE DA PAIXAO SANTOS,JOSIANE DA PAIXAO SANTOS,RQR2G28,LEONARDO,CHAMADA,Ranking
2,512327,110579,2022-01-05,02:00:00,FABRICA,ITABATAN,32.812,SIDNEY JUSTO DOS SANTOS,SIDNEY JUSTO DOS SANTOS,RQR2G28,LEONARDO,CHAMADA,Ranking

In [5]:
display(df_DPG.shape)
display(df_excelencia.shape)
display(df_Marlin.shape)
display(df_ranking.shape)

(780, 13)

(14194, 13)

(239, 13)

(4714, 13)

In [6]:
df_para_combinar = [df_DPG, df_excelencia, df_Marlin, df_ranking]

In [7]:
df_combinado = pd.concat(df_para_combinar)

In [8]:
df_combinado

,ST,C. CUSTO,DATA,HORA,ORIGEM,DESTINO,VALOR TOTAL,SOLICITANTE,PASSAGEIRO,PLACA,MOTORISTA,TIPO,profit
0,511878/511570/511857/511868/511862,110402/110846/110086/110086/110846/110888,2022-05-16 00:00:00,06:30:00,CARAVELAS,FABRICA,330.00,EMMANUEL SILVA DE ANDRADE,EMMANUEL SILVA DE ANDRADE,ETIOS,CRISTOGENES,CHAMADA,DPG
1,512162/512131/512206,110085/110086/110096,2022-06-09 00:00:00,18:00:00,CONCEIÇÃO DA BARRA COCB,TEIXEIRA DE FREITAS,460.00,FERNANDA FERREIRA CONTARDI,FERNANDA FERREIRA CONTARDI,ETIOS,CRISTOGENES,CHAMADA,DPG
2,E-MAIL,110065,2022-06-10 00:00:00,18:00:00,CONCEIÇÃO DA BARRA COCB,TEIXEIRA DE FREITAS,460.00,FERNANDA FERREIRA CONTARDI,FERNANDA FERREIRA CONTARDI,ETIOS,CRISTOGENES,CHAMADA,DPG
3,512417/512492/512410,110065/110074/160067,2022-06-22 00:00:00,18:00:00,CONCEIÇÃO DA BARRA COCB,TEIXEIRA DE FREITAS,460.00,FERNANDA FERREIRA CONTARDI,FERNANDA FERREIRA CONTARDI,ETIOS,CRISTOGENES,CHAMADA,DPG
4,518292,110090,2022-01-04 00:00:00,19:00:00,FABRICA,TEIXEIRA DE FREITAS,185.00,MURILO VIANA/VILMAR SOUZA/MARCUS VINICIUS E JE...,MURILO VIANA/VILMAR SOUZA/MARCUS VINICIUS E JE...,ETIOS,CRISTOGENES,CHAMADA,DPG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4709,600616,110100,2022-09-09 00:00:00,19:00:00,FABRICA,ITABATÃ,170.91,AVERALDO SILVA,PASSAGEIROS DIVERSOS,RBS0B72,LEONARDO,NaN,Ranking
4710,601773,110086,2022-09-09 00:00:00,17:48:00,MUCURI,FABRICA,227.87,MARCOS FERREIRA,GUILHERME LUCAS BATISTA,RQR2G23,TIAGO,NaN,Ranking
4711,601314,08BCMUC,2022-09-09 00:00:00,08:00:00,MUCURI,SERRA,782.69,BRENO BRITO,BRENO BRITO,RQO3H31,AGNALDO,NaN,Ranking
4712,600730,01CPCOR114,2022-09-09 00:00:00,08:00:00,VITORIA,CONCEIÇÃO DA BARRA,782.69,PATRICK BRUNELI,PATRICK BRUNELI,RQO3H31,AGNALDO,NaN,Ranking
4713,599133,10CECER071,2022-09-09 00:00:00,09:00:00,PORTO SEGURO,ITABATÃ,1384.70,LEANDRO NASCIMENTO,LEANDRO NASCIMENTO,RBI6G68,SERGIO,NaN,Ranking

## Transformações na coluna 'ORIGEM'

In [9]:
df_combinado.columns

Index(['ST', 'C. CUSTO', 'DATA', 'HORA', 'ORIGEM', 'DESTINO', 'VALOR TOTAL',
       'SOLICITANTE', 'PASSAGEIRO', 'PLACA', 'MOTORISTA', 'TIPO', 'profit'],
      dtype='object')

In [10]:
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.upper()
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.strip()

In [11]:
df_combinado['ORIGEM'].unique()

array(['CARAVELAS', 'CONCEIÇÃO DA BARRA COCB', 'FABRICA', 'ITABATÃ',
       'POSTO DA MATA', 'RANCHO ALEGRE', 'SÃO JOSÉ DE ALCOBAÇA',
       'SITIO RAIZES', 'TEIXEIRA   DE  FREITAS', 'TEIXEIRA', 'ITABATA',
       'MUCURI', 'VITORIA', 'SÃO MATEUS', 'TEIXEIRA DE FREITAS',
       'ITABATAN', 'CRUZELÂNDIA', 'CONCEIÇÃO DA BARRA', 'PEDRO CANÁRIO',
       'GURIRI', 'BRAÇO DO RIO', 'DIVISA BA/ES', 'SAYONARA',
       'PORTO SEGURO', 'ARACRUZ', 'NANUQUE', 'EUNAPOLIS',
       'CACHOEIRO DE ITAPEMIRIM', 'ITAUNAS', 'NOVA VENÉCIA', 'FÁBRICA',
       'NOVA VIÇOSA', 'POUSADA RIO MUCURI', 'VITÓRIA',
       'CACHOEIRO ITAPEMIRIM', 'TEIXEIRA DE FREIRAS',
       'CONCEIÇAO DA BARRA', 'FÁBRIA', 'CRISTAL DO NORTE', 'DIVISA-BA-ES',
       'NOVA VENECIA', 'CURVELO', 'HOSP. PAINEIRAS', 'PEDRO CANARIO',
       'VERACEL EUNAPOLIS', 'LINHARES', 'FÁBRICA MU', 'MUCURI - BA',
       'ITABATÃ - BA', 'VITÓRIA - ES', 'SÃO MATEUS - ES',
       'POSTO DA MATA - BA', 'TEIXEIRA DE FREITAS - BA', 'TRAJETO EXTRA',
       'PORTO SEGURO - BA', 'CARAVELAS - BA', 'VITÓRIA/AEROPORTO - ES',
       'POUSADA RIO MUCURI - BA', 'LINHARES - ES',
       'VITÓRIA - ES/AEROPORTO', 'GURIRI - ES', 'CONCEIÇÃO DA BARRA - ES',
       'PEDRO CANÁRIO - ES', 'BRAÇO DO RIO - ES', 'SERRA - ES',
       'ARACRUZ - ES', 'NOVA VIÇOSA - BA', 'SAYONARA - ES',
       'RANCHO ALEGRE - BA', 'NANUQUE - MG', 'EUNÁPOLIS - BA',
       'ITAMARAJU - BA', 'TEIXEIRA DE FREITAS - AEROPORTO',
       'CRUZELÂNDIA - BA', 'VILA VELHA - ES', 'FÁBRICA-MU',
       'FABRICA/INTERNO - MU', 'VITÓRIA-ES', 'FABRICA MU',
       'SÃO JOSE DE ALCOBAÇA - BA', 'PORTO SEGURO  - BA', 'C. ITAPEM',
       'V. VELHA', 'VITÓRIA/ES', 'CACH. ITAP.', 'CARIACICA', 'SERRA/ES',
       'C.ITAPEM.', 'IBIRAÇU', 'VILA VELHA', 'GUARAPARI', 'B. GUANDÚ',
       'DIRETORIA', 'C. ITAPEMIRIM', 'ECO FLORESTA', 'VITÓRIIA',
       'C.ITAPEMIRIM', 'AEROPORTO VITÓRIA', 'HANGAR LIDER',
       'CACH. ITAPEMIRIM', 'IBIS HOTEL VITÓRIA', 'VITORIA AEROPORTO',
       'CRUZELANDIA', 'AERODROMO', 'DIVISA', 'CMC', 'IPATINGA',
       'TEIXEIRA DE FREITA', 'SERRA'], dtype=object)

In [12]:
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("   "," ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("  "," ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("    "," ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("ITABATAN","ITABATÃ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("FABRICA","FÁBRICA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("VITORIA","VITÓRIA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("CRUZELANDIA","CRUZELÂNDIA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("VITÓRIIA","VITÓRIA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("ITAUNAS","ITAÚNAS")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("CACH. ITAP.","CACHOEIRO DE ITAPEMIRIM")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C. ITAPEMIRIM","CACHOEIRO DE ITAPEMIRIM")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("TEIXEIRA DE FREITA","TEIXEIRA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("CACHOEIRO ITAPEMIRIM","CACHOEIRO DE ITAPEMIRIM")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("CANARIO","CANÁRIO")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("JOSE","JOSÉ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("DIVISA-BA-ES","DIVISA BA/ES")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("TEIXEIRA DE FREIRAS","TEIXEIRA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("TEIXEIRA","TEIXEIRA DE FREITAS")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("ITABATA","ITABATÃ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C. ITAPEM","CACHOEIRO DE ITAPEMIRIM")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C.ITAPEMIRIM","C.ITAPEM.")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C.ITAPEM.","CACHOEIRO DE ITAPEMIRIM")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("EUNAPOLIS","EUNÁPOLIS")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("V. VELHA","VILA VELHA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("B. GUANDÚ","BAIXO GUANDÚ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("HOTEL","HOTÉL")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("SS","S")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("FÁBRIA","FÁBRICA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("FÁBRICA- MU","FÁBRICA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("FÁBRICA", "FÁBRICA - UNIDADE MUCURI")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace(" - ES","")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace(" - BA","")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace(" - MG","")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("NOVA VENECIA","NOVA VENÉCIA")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("SERRA/ES","SERRA")

C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("CACH. ITAP.","CACHOEIRO DE ITAPEMIRIM")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C. ITAPEMIRIM","CACHOEIRO DE ITAPEMIRIM")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C. ITAPEM","CACHOEIRO DE ITAPEMIRIM")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C.ITAPEMIRIM","C.ITAPEM.")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:22: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("C.ITAPEM.","CACHOEIRO DE ITAPEMIRIM")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:24: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("V. VELHA","VILA VELHA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\699028480.py:25: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("B. GUANDÚ","BAIXO GUANDÚ")

In [13]:
df_combinado['ORIGEM'].unique()

array(['CARAVELAS', 'CONCEIÇÃO DA BARRA COCB', 'FÁBRICA - UNIDADE MUCURI',
       'ITABATÃ', 'POSTO DA MATA', 'RANCHO ALEGRE',
       'SÃO JOSÉ DE ALCOBAÇA', 'SITIO RAIZES', 'TEIXEIRA DE FREITAS',
       'MUCURI', 'VITÓRIA', 'SÃO MATEUS', 'CRUZELÂNDIA',
       'CONCEIÇÃO DA BARRA', 'PEDRO CANÁRIO', 'GURIRI', 'BRAÇO DO RIO',
       'DIVISA BA/ES', 'SAYONARA', 'PORTO SEGURO', 'ARACRUZ', 'NANUQUE',
       'EUNÁPOLIS', 'CACHOEIRO DE ITAPEMIRIM', 'ITAÚNAS', 'NOVA VENÉCIA',
       'NOVA VIÇOSA', 'POUSADA RIO MUCURI', 'CONCEIÇAO DA BARRA',
       'CRISTAL DO NORTE', 'CURVELO', 'HOSP. PAINEIRAS',
       'VERACEL EUNÁPOLIS', 'LINHARES', 'FÁBRICA - UNIDADE MUCURI MU',
       'TRAJETO EXTRA', 'VITÓRIA/AEROPORTO', 'SERRA', 'ITAMARAJU',
       'TEIXEIRA DE FREITAS - AEROPORTO', 'VILA VELHA',
       'FÁBRICA - UNIDADE MUCURI-MU',
       'FÁBRICA - UNIDADE MUCURI/INTERNO - MU', 'VITÓRIA-ES',
       'VITÓRIA/ES', 'CARIACICA', 'IBIRAÇU', 'GUARAPARI', 'BAIXO GUANDÚ',
       'DIRETORIA', 'ECO FLORESTA', 'AEROPORTO VITÓRIA', 'HANGAR LIDER',
       'CACHOEIRO DE ITAPEMIRIMMIRIM', 'IBIS HOTÉL VITÓRIA',
       'VITÓRIA AEROPORTO', 'AERODROMO', 'DIVISA', 'CMC', 'IPATINGA'],
      dtype=object)

## Transformações na coluna 'DESTINO'

In [14]:
df_combinado['DESTINO'].unique()

array(['FABRICA', 'TEIXEIRA DE FREITAS', 'POSTO DA MATA', 'ITABATA',
       'POSTO DA MATA ', 'AEROPORTO', 'SÃO JOSÉ DE ALCOBAÇA',
       'PEDRO CANÁRIO', 'CMC MUCURI X ITABATAN', 'FABRICA ',
       'CONCEIÇÃO DA BARRA COCB', 'MUCURI', 'ITABATÃ CMC', 'TEIXEIRA',
       'PEDRO CANARIO', 'VITORIA', 'SÃO MATEUS',
       'TEIXEIRA/RAMAGRAF/MODULO3 PICADAO/POSTO DA MATA/TEIXEITA ATE AS 17:10',
       'ITABATAN', 'GURIRI', 'CONCEIÇÃO DA BARRA', 'ITABATÃ',
       'BRAÇO DO RIO', 'SAYONARA', 'VITÓRIA', 'ARACRUZ', 'SERRA',
       'DIVISA', 'AÉRODROMO MAX FEFFER', 'CRISTAL DO NORTE', 'LINHARES',
       'CACHOEIRO ITAPEMIRIM', 'CARAVELAS', 'MUCURI ', 'CRUZELANDIA',
       'SITIO RAIZES', 'SÍTIO RAIZES', 'PORTO SEGURO', 'DIVISA BA/ES',
       'FÁBRICA', 'COCB', 'DIVERSOS', 'CACHOEIRA ITAPEMIRIM',
       'POSTO FLORESTA', 'NOVA VIÇOSA', 'SALOMÃO BRUNO FIGUEREDO',
       'RANCHO ALEGRE', 'PEDRO CANÁRIO/ IDA  E VOLTA',
       'CACHOEIRO ITAPEMIR.', 'CRUZELÂNDIA', 'GUIRIRI', 'ARACRUZ/ GURIRI',
       'CARLOS CHAGAS', 'NOVA VENECIA', 'VIX-AEROPORTO', 'CURVELO-MG',
       'NANUQUE', 'EUNAPOLIS', 'CONCEIÇÃO  DA BARRA', 'VILA VELHA',
       'CACHOEIRO DE ITAPEMIRIM', 'TREVO DA BARRA', 'CRUZELANDIA/DIVISA',
       'ITABATAN/MUCURI', 'TREVO DE POSTO DA AMATA', 'INTERNO',
       'TREVO DE POSTO DA MATA', 'SERRA/JARDIM AMERICA',
       'Posto Da Mata - BA', 'Itabatã - BA', 'Mucuri - BA',
       'Teixeira De Freitas - BA', 'Guriri - ES', 'Pedro Canário - ES',
       'São Mateus - ES', 'Braço Do Rio - ES', 'Sayonara - ES',
       'Vitória - ES/Aeroporto', 'Conceição Da Barra - ES', 'Fábrica MU',
       'Aracruz - ES', 'Vitória - ES', 'Trajeto Extra', 'Serra - ES',
       'Mucuri-BA', 'Nova Viçosa - BA', 'Taquari - BA', 'AEROPORTO -VIX',
       'SAO MATEUS', 'FABRICA MU', 'PEDRO CANÁRIO - ES',
       'FABRICA/INTERNO - MU', 'POSTO DA MATA - BA', 'MUCURI - BA',
       'AEROPORTO VIX', '(TEIXEIRA ARACRUZ)', 'AEROPORTO-VIX',
       'VITÓRIA-ES', 'SÃO MATEUS - ES', '(ATENDIMENTO DUSTER )',
       '(ATEND. DIRETORIA )', 'IBIRAÇÚ-ES', 'TEIXEIRA DE FREITAS - BA',
       'CONCEIÇÃO DA BARRA - ES', '( ATEND. DIRETORIA )', 'ITABATÃ - BA',
       '(TEIXEIRA - ARACRUZ)', 'POUSADA RIO MUCURI',
       '( TEIXEIRA -ARACRUZ)', 'ARACRUZ - ES', '(ATENDIMENTO  DUSTER)',
       'VITÓRIA/AEROPORTO - ES', '(MUCURI/ NOVA VIÇOSA)', 'GURIRI - ES',
       '( TEIXEIRA / ARACRUZ )', '( ITABATAN-ARACRUZ)',
       '(NOVA VIÇOSA-SÃO MATEUS)', 'BRAÇO DO RIO - ES',
       '(MUCURI- LINHARES)', 'SERRA - ES', 'POSTO  DA MATA',
       '(MUCURI-NOVA VIÇOSA)', '(NOVA VIÇOSA-MUCURI)', 'BRAÇO DO  RIO',
       '( PEDRO  CANÁRIO-ARACRUZ)', '(ITABATAN-BRAÇO DO RIO)',
       '( PROJETO RIO DO SUL)', 'VIVEIRO (ITABATAN)',
       '( TEIXEIRA / ARACRUZ)', '(VITÓRIA-COLATINA)',
       '( ITABATAN- ARACRUZ)', 'ITAMARAJU - BA',
       '( TEIXEIRA -PEDRO CANÁRIO)', '( PEDRO  CANÁRIO-TEIXEIRA)',
       '(SÃO MATEUS- SERRA)', '( FÁBRICA  PRADO', '(PRADO -MUCURI)',
       '(MUCURI - ITAMARAJÚ)', '(ITAMARAJU - MUCURI )', 'PEDRO  CANÁRIO',
       '(TEIXEIRA / ARACRUZ )', '(ITABATAN / ARACRUZ )',
       '( SERRA  -ITABATAN)', '( VITÓRIA -NOVA VIÇOSA )',
       '( MUCURI- LINHARES)', 'CONCEIÇAO DA BARRA',
       '( CONCEIÇÃO D BARRA-ITABTAN)', '( ITABATAN- GURIRI )',
       'PEDRO  CANARIO', '(TEIXEIRA/ TEIXEIRA )', '(  TEIXEIRA- PRADO )',
       'NOVA VIÇOSA - BA', 'Nanuque - MG', 'Vitória-ES',
       'Porto Seguro  - BA', 'Eunápolis - BA',
       'Teixeira De Freitas - Aeroporto', 'Linhares - ES',
       'Fabrica/Interno - MU', 'Fabrica MU', 'Vitória/Aeroporto - ES',
       '(FABRICA/ARACRUZ) (DESVIO)', 'SÃO JOSE DE ALCOBAÇA',
       'EUNÁPOLIS - BA', '(VITORIA/MUCURI)', '(VITORIA/ITABATÃI)',
       '(VITORIA/TEIXEIRA) (DESVIO)', '(SÃO MATEUS/POSTO DA MATA)',
       '(SÃO MATEUS/TEIXEIRA)', '(POSTO DA MATA/VITORIA) (DESVIO)',
       '(GURIRI/VITORIA) (DESVIO)', '(ITABATÃ/VITORIA) (DESVIO)',
       '(TEIXEIRA/VITORIA)', 'ATENDIMENTO A DIRETORIA',
       'CONCEIÇAÕ DA BARRA', '(MUCURI/VITORIA) (DESVIO)',
       '(MUCURI/PORTO SEGURO)', 'AERODROMO', '(VITORIA/SAO MATEUS)',
       '(ITABATA/PORTO SEGURO)', '(CARLOS CHAGAS/SÃO MATEUS)',
       '(FABRICA/CARLOS CHAGAS)', '(FABRICA/CRISTAL)',
       '(ITABATA/VITORIA)', '(VITORIA/PEDRO CANARIO)',
       '(TEIXEIRA/JUERANA)', '(TEIXEIRA/ARACRUZ)', '(ITABATA/GURIRI)',
       '(FABRICA/NOVA VENECIA)', '(N. VENECIA/FABRICA)',
       '(ITABATA/P.CANARIO/TEIXEIRA)', '(FABRICA/CARAVELAS)',
       '(SERRA/TEIXEIRA)', '(P. CANARIO/ITABATA)', 'RIO MUCURI',
       'CONCEIÇAO DA BARRA (DESVIO)', '(FABRICA/MONTANHA)',
       '(P. CANARIO/BRAÇO DO RIO)', '(CON. DA BARRA/ VITORIA)',
       "PEDRA D'AGUA", '(SÃO MATEUS/GURIRI)',
       '(ITABATÃ/ARACRUZ) (DESVIO)', '(FABRICA/VITORIA)', 'FÁBRICA MU',
       '(P. SEGURO/MUCURI)', '(FABRICA/VITORIA) (DESVIO)',
       '(CONC. DA BARRA/ SÃO MATEUS)', 'POUS.RIO MUC', 'TEIX. FREITAS',
       'PED. CANÁRIO', 'NOVA VENÉCIIA', 'G. VALADARES', 'POSTO MATA',
       'FABR. MUC', 'P.R. MUCURI', 'P. CANÁRIO', 'S. MATEUS', 'P. MATA',
       '´MUCURI', 'T. FREITAS', 'VITÓRIA/ES', 'GUARAPARI', 'DIRETORIA',
       'S.MATEUS', 'COLATINA', 'ECO FLORESTA', 'FABRICA MUC',
       'CONCEIÇÃO BARRA', 'HANGAR LÍDER', 'SANTA TERESA',
       'FABRICA MUCURI', '´PEDRO CANÁRIO', 'VITORIA AEROPORTO',
       'BRAÇO DO RIO ', 'PORTO SEGURO ', 'POSTO DA MATA  ',
       'CRUZENLANDIA', 'VITORIA/AEROPORTO', 'SÃO MATEUS ',
       'RANCHO ALGRE ', 'fABRICA', 'RANCHO ALEGRE ', 'CRUZELANDIA ',
       'BRACO DO RIO', 'VITÓRIA ', 'CRISTAL DO NORTE ', 'SAYNARA',
       'FÁBRICA ', 'SÃO MATUES', 'TEXEIRA DE FREITAS ',
       'CONCEIÇÃO DA BARRA ', 'CACHOEIRO DO ITAPEMIRIM', 'CMC'],
      dtype=object)

In [15]:
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("(","")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace(")","")

C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\1938246535.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("(","")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\1938246535.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace(")","")

In [16]:
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.upper()
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.strip()

In [17]:
df_combinado['DESTINO'].unique()

array(['FABRICA', 'TEIXEIRA DE FREITAS', 'POSTO DA MATA', 'ITABATA',
       'AEROPORTO', 'SÃO JOSÉ DE ALCOBAÇA', 'PEDRO CANÁRIO',
       'CMC MUCURI X ITABATAN', 'CONCEIÇÃO DA BARRA COCB', 'MUCURI',
       'ITABATÃ CMC', 'TEIXEIRA', 'PEDRO CANARIO', 'VITORIA',
       'SÃO MATEUS',
       'TEIXEIRA/RAMAGRAF/MODULO3 PICADAO/POSTO DA MATA/TEIXEITA ATE AS 17:10',
       'ITABATAN', 'GURIRI', 'CONCEIÇÃO DA BARRA', 'ITABATÃ',
       'BRAÇO DO RIO', 'SAYONARA', 'VITÓRIA', 'ARACRUZ', 'SERRA',
       'DIVISA', 'AÉRODROMO MAX FEFFER', 'CRISTAL DO NORTE', 'LINHARES',
       'CACHOEIRO ITAPEMIRIM', 'CARAVELAS', 'CRUZELANDIA', 'SITIO RAIZES',
       'SÍTIO RAIZES', 'PORTO SEGURO', 'DIVISA BA/ES', 'FÁBRICA', 'COCB',
       'DIVERSOS', 'CACHOEIRA ITAPEMIRIM', 'POSTO FLORESTA',
       'NOVA VIÇOSA', 'SALOMÃO BRUNO FIGUEREDO', 'RANCHO ALEGRE',
       'PEDRO CANÁRIO/ IDA  E VOLTA', 'CACHOEIRO ITAPEMIR.',
       'CRUZELÂNDIA', 'GUIRIRI', 'ARACRUZ/ GURIRI', 'CARLOS CHAGAS',
       'NOVA VENECIA', 'VIX-AEROPORTO', 'CURVELO-MG', 'NANUQUE',
       'EUNAPOLIS', 'CONCEIÇÃO  DA BARRA', 'VILA VELHA',
       'CACHOEIRO DE ITAPEMIRIM', 'TREVO DA BARRA', 'CRUZELANDIA/DIVISA',
       'ITABATAN/MUCURI', 'TREVO DE POSTO DA AMATA', 'INTERNO',
       'TREVO DE POSTO DA MATA', 'SERRA/JARDIM AMERICA',
       'POSTO DA MATA - BA', 'ITABATÃ - BA', 'MUCURI - BA',
       'TEIXEIRA DE FREITAS - BA', 'GURIRI - ES', 'PEDRO CANÁRIO - ES',
       'SÃO MATEUS - ES', 'BRAÇO DO RIO - ES', 'SAYONARA - ES',
       'VITÓRIA - ES/AEROPORTO', 'CONCEIÇÃO DA BARRA - ES', 'FÁBRICA MU',
       'ARACRUZ - ES', 'VITÓRIA - ES', 'TRAJETO EXTRA', 'SERRA - ES',
       'MUCURI-BA', 'NOVA VIÇOSA - BA', 'TAQUARI - BA', 'AEROPORTO -VIX',
       'SAO MATEUS', 'FABRICA MU', 'FABRICA/INTERNO - MU',
       'AEROPORTO VIX', 'TEIXEIRA ARACRUZ', 'AEROPORTO-VIX', 'VITÓRIA-ES',
       'ATENDIMENTO DUSTER', 'ATEND. DIRETORIA', 'IBIRAÇÚ-ES',
       'TEIXEIRA - ARACRUZ', 'POUSADA RIO MUCURI', 'TEIXEIRA -ARACRUZ',
       'ATENDIMENTO  DUSTER', 'VITÓRIA/AEROPORTO - ES',
       'MUCURI/ NOVA VIÇOSA', 'TEIXEIRA / ARACRUZ', 'ITABATAN-ARACRUZ',
       'NOVA VIÇOSA-SÃO MATEUS', 'MUCURI- LINHARES', 'POSTO  DA MATA',
       'MUCURI-NOVA VIÇOSA', 'NOVA VIÇOSA-MUCURI', 'BRAÇO DO  RIO',
       'PEDRO  CANÁRIO-ARACRUZ', 'ITABATAN-BRAÇO DO RIO',
       'PROJETO RIO DO SUL', 'VIVEIRO ITABATAN', 'VITÓRIA-COLATINA',
       'ITABATAN- ARACRUZ', 'ITAMARAJU - BA', 'TEIXEIRA -PEDRO CANÁRIO',
       'PEDRO  CANÁRIO-TEIXEIRA', 'SÃO MATEUS- SERRA', 'FÁBRICA  PRADO',
       'PRADO -MUCURI', 'MUCURI - ITAMARAJÚ', 'ITAMARAJU - MUCURI',
       'PEDRO  CANÁRIO', 'ITABATAN / ARACRUZ', 'SERRA  -ITABATAN',
       'VITÓRIA -NOVA VIÇOSA', 'CONCEIÇAO DA BARRA',
       'CONCEIÇÃO D BARRA-ITABTAN', 'ITABATAN- GURIRI', 'PEDRO  CANARIO',
       'TEIXEIRA/ TEIXEIRA', 'TEIXEIRA- PRADO', 'NANUQUE - MG',
       'PORTO SEGURO  - BA', 'EUNÁPOLIS - BA',
       'TEIXEIRA DE FREITAS - AEROPORTO', 'LINHARES - ES',
       'FABRICA/ARACRUZ DESVIO', 'SÃO JOSE DE ALCOBAÇA', 'VITORIA/MUCURI',
       'VITORIA/ITABATÃI', 'VITORIA/TEIXEIRA DESVIO',
       'SÃO MATEUS/POSTO DA MATA', 'SÃO MATEUS/TEIXEIRA',
       'POSTO DA MATA/VITORIA DESVIO', 'GURIRI/VITORIA DESVIO',
       'ITABATÃ/VITORIA DESVIO', 'TEIXEIRA/VITORIA',
       'ATENDIMENTO A DIRETORIA', 'CONCEIÇAÕ DA BARRA',
       'MUCURI/VITORIA DESVIO', 'MUCURI/PORTO SEGURO', 'AERODROMO',
       'VITORIA/SAO MATEUS', 'ITABATA/PORTO SEGURO',
       'CARLOS CHAGAS/SÃO MATEUS', 'FABRICA/CARLOS CHAGAS',
       'FABRICA/CRISTAL', 'ITABATA/VITORIA', 'VITORIA/PEDRO CANARIO',
       'TEIXEIRA/JUERANA', 'TEIXEIRA/ARACRUZ', 'ITABATA/GURIRI',
       'FABRICA/NOVA VENECIA', 'N. VENECIA/FABRICA',
       'ITABATA/P.CANARIO/TEIXEIRA', 'FABRICA/CARAVELAS',
       'SERRA/TEIXEIRA', 'P. CANARIO/ITABATA', 'RIO MUCURI',
       'CONCEIÇAO DA BARRA DESVIO', 'FABRICA/MONTANHA',
       'P. CANARIO/BRAÇO DO RIO', 'CON. DA BARRA/ VITORIA',
       "PEDRA D'AGUA", 'SÃO MATEUS/GURIRI', 'ITABATÃ/ARACRUZ DESVIO',
       'FABRICA/VITORIA', 'P. SEGURO/MUCURI', 'FABRICA/VITORIA DESVIO',
       'CONC. DA BARRA/ SÃO MATEUS', 'POUS.RIO MUC', 'TEIX. FREITAS',
       'PED. CANÁRIO', 'NOVA VENÉCIIA', 'G. VALADARES', 'POSTO MATA',
       'FABR. MUC', 'P.R. MUCURI', 'P. CANÁRIO', 'S. MATEUS', 'P. MATA',
       '´MUCURI', 'T. FREITAS', 'VITÓRIA/ES', 'GUARAPARI', 'DIRETORIA',
       'S.MATEUS', 'COLATINA', 'ECO FLORESTA', 'FABRICA MUC',
       'CONCEIÇÃO BARRA', 'HANGAR LÍDER', 'SANTA TERESA',
       'FABRICA MUCURI', '´PEDRO CANÁRIO', 'VITORIA AEROPORTO',
       'CRUZENLANDIA', 'VITORIA/AEROPORTO', 'RANCHO ALGRE',
       'BRACO DO RIO', 'SAYNARA', 'SÃO MATUES', 'TEXEIRA DE FREITAS',
       'CACHOEIRO DO ITAPEMIRIM', 'CMC'], dtype=object)

In [18]:
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("   "," ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("  "," ")
df_combinado['ORIGEM'] = df_combinado['ORIGEM'].str.replace("    "," ")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. SEGURO","PORTO SEGURO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("MUCURIC","MUCURI")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FÁBRICA MUCURIC","FÁBRICA MUCURI")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. CANARIO","PEDRO CANÁRIO")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. CANARIO","PEDRO CANÁRIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("BRACO DO RIO","BRAÇO DO RIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("SÃO MATUES","SÃO MATEUS")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("T. FREITAS","TEIXEIRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("TEIXEIRA DE FREITAS","TEIXEIRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("´PEDRO CANÁRIO","PEDRO CANÁRIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CONC. DA BARRA","CONCEIÇÃO DA BARRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CONCEIÇÃO BARRA","CONCEIÇÃO DA BARRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("VITORIA","VITÓRIA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("SAYNARA","SAYONARA")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CACHOEIRO DO ITAPEMIRIM","CACHOEIRO DE ITAPEMIRIM")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("´MUCURI","MUCURI")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CRUZENLANDIA","CRUZELÂNDIA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATA","ITABATÃ")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FABRICA","FÁBRICA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("PED. CANÁRIO","PEDRO CANÁRIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("SAO MATEUS","SÃO MATEUS")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CACHOEIRO ITAPEMIR.","CACHOEIRO DE ITAPEMIRIM")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CRUZELANDIA","CRUZELÂNDIA")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CON. DA BARRA","CONCEIÇÃO DA BARRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("TEIX. FREITAS","TEIXEIRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("TEIXEITA ","TEIXEIRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("TEIXEIRA","TEIXEIRA DE FREITAS")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("PEDRO CANARIO","PEDRO CANÁRIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("POSTO MATA","POSTO DA MATA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("G. VALADARES","GOVERNADOR VALADARES")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("NOVA VENÉCIIA","NOVA VENÉCIA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. CANÁRIO","PEDRO CANÁRIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("S. MATEUS","SÃO MATEUS")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. MATA","POSTO DA MATA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CONCEIÇAO DA BARRA","CONCEIÇÃO DA BARRA")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("S.MATEUS","SÃO MATEUS")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("AMERICA","AMÉRICA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃN","ITABATÃ")


df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("N. VENECIA","NOVA VENÉCIA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃN","ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃN","ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FÁBRICA MUCURI","FÁBRICA MU")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("VITÓRIA AEROPORTO","VITÓRIA/AEROPORTO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FÁBRICA MU","FÁBRICA MUCURI")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FABR. MUC","FÁBRICA MUCURI")


df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace(" - ES","")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace(" - BA","")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace(" - MG","")


df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("/ES","")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("/INTERNO - MU","* MUCURI INTERNO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃI","ITABATÃ")


df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- PRADO","/PRADO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃI","ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("/INTERNO - MU","* MUCURI INTERNO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃI","ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("/INTERNO - MU","* MUCURI INTERNO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃI","ITABATÃ")


df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- SERRA","/SERRA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABATÃI","ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-COLATINA","/COLATINA")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-ARACRUZ","/ARACRUZ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-MUCURI","/MUCURI")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-ARACRUZ","/ARACRUZ")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ITABTAN","ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-ITABATÃ","/ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- LINHARES","/ LINHARES")


df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-PEDRO CANÁRIO","/PEDRO CANÁRIO")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-ES","")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("ATE AS 17:10","")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- MUCURI","/ MUCURI")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- ITAMARAJÚ","/ ITAMARAJÚ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-SÃO MATEUS","/SÃO MATEUS")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- ARACRUZ","/ ARACRUZ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-NOVA VIÇOSA","/NOVA VIÇOSA")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-TEIXEIRA DE FREITAS","/TEIXEIRA DE FREITAS")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-BRAÇO DO RIO","/BRAÇO DO RIO")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("X ITABATÃ","/ ITABATÃ")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FÁBRICA  PRADO","FÁBRICA / PRADO")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("EUNAPOLIS","EUNÁPOLIS")

df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("-BA","")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("- GURIRI","/ GURIRI")
df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("/ IDA  E VOLTA","")

C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. SEGURO","PORTO SEGURO")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. CANARIO","PEDRO CANÁRIO")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. CANARIO","PEDRO CANÁRIO")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("T. FREITAS","TEIXEIRA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CONC. DA BARRA","CONCEIÇÃO DA BARRA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("PED. CANÁRIO","PEDRO CANÁRIO")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:29: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CACHOEIRO ITAPEMIR.","CACHOEIRO DE ITAPEMIRIM")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:32: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("CON. DA BARRA","CONCEIÇÃO DA BARRA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:33: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("TEIX. FREITAS","TEIXEIRA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:38: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("G. VALADARES","GOVERNADOR VALADARES")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:41: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. CANÁRIO","PEDRO CANÁRIO")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:42: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("S. MATEUS","SÃO MATEUS")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:43: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("P. MATA","POSTO DA MATA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:46: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("S.MATEUS","SÃO MATEUS")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:52: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("N. VENECIA","NOVA VENÉCIA")
C:\Users\Markos Alves\AppData\Local\Temp\ipykernel_42824\3370867562.py:59: FutureWarning: The default value of regex will change from True to False in a future version.
  df_combinado['DESTINO'] = df_combinado['DESTINO'].str.replace("FABR. MUC","FÁBRICA MUCURI")

In [19]:
df_combinado['DESTINO'].unique()

array(['FÁBRICA', 'TEIXEIRA DE FREITAS', 'POSTO DA MATA', 'ITABATÃ',
       'AEROPORTO', 'SÃO JOSÉ DE ALCOBAÇA', 'PEDRO CANÁRIO',
       'CMC MUCURI / ITABATÃ', 'CONCEIÇÃO DA BARRA COCB', 'MUCURI',
       'ITABATÃ CMC', 'VITÓRIA', 'SÃO MATEUS',
       'TEIXEIRA DE FREITAS/RAMAGRAF/MODULO3 PICADAO/POSTO DA MATA/TEIXEIRA DE FREITAS',
       'GURIRI', 'CONCEIÇÃO DA BARRA', 'BRAÇO DO RIO', 'SAYONARA',
       'ARACRUZ', 'SERRA', 'DIVISA', 'AÉRODROMO MAX FEFFER',
       'CRISTAL DO NORTE', 'LINHARES', 'CACHOEIRO DE ITAPEMIRIMM',
       'CARAVELAS', 'CRUZELÂNDIA', 'SITIO RAIZES', 'SÍTIO RAIZES',
       'PORTO SEGURO', 'DIVISA BA', 'COCB', 'DIVERSOS',
       'CACHOEIRA ITAPEMIRIM', 'POSTO FLORESTA', 'NOVA VIÇOSA',
       'SALOMÃO BRUNO FIGUEREDO', 'RANCHO ALEGRE',
       'CACHOEIRO DE ITAPEMIRIM', 'GUIRIRI', 'ARACRUZ/ GURIRI',
       'CARLOS CHAGAS', 'NOVA VENECIA', 'VIX-AEROPORTO', 'CURVELO-MG',
       'NANUQUE', 'EUNÁPOLIS', 'CONCEIÇÃO  DA BARRA', 'VILA VELHA',
       'TREVO DA BARRA', 'CRUZELÂNDIA/DIVISA', 'ITABATÃ/MUCURI',
       'TREVO DE POSTO DA AMATA', 'INTERNO', 'TREVO DE POSTO DA MATA',
       'SERRA/JARDIM AMÉRICA', 'VITÓRIA/AEROPORTO', 'FÁBRICA MUCURI',
       'TRAJETO EXTRA', 'TAQUARI', 'AEROPORTO -VIX',
       'FÁBRICA* MUCURI INTERNO', 'AEROPORTO VIX',
       'TEIXEIRA DE FREITAS ARACRUZ', 'AEROPORTO-VIX',
       'ATENDIMENTO DUSTER', 'ATEND. DIRETORIA', 'IBIRAÇÚ',
       'TEIXEIRA DE FREITAS / ARACRUZ', 'POUSADA RIO MUCURI',
       'TEIXEIRA DE FREITAS /ARACRUZ', 'ATENDIMENTO  DUSTER',
       'MUCURI/ NOVA VIÇOSA', 'ITABATÃ/ARACRUZ', 'NOVA VIÇOSA/SÃO MATEUS',
       'MUCURI/ LINHARES', 'POSTO  DA MATA', 'MUCURI/NOVA VIÇOSA',
       'NOVA VIÇOSA/MUCURI', 'BRAÇO DO  RIO', 'PEDRO  CANÁRIO/ARACRUZ',
       'ITABATÃ/BRAÇO DO RIO', 'PROJETO RIO DO SUL', 'VIVEIRO ITABATÃ',
       'VITÓRIA/COLATINA', 'ITABATÃ/ ARACRUZ', 'ITAMARAJU',
       'TEIXEIRA DE FREITAS /PEDRO CANÁRIO',
       'PEDRO  CANÁRIO/TEIXEIRA DE FREITAS', 'SÃO MATEUS/SERRA',
       'FÁBRICA / PRADO', 'PRADO /MUCURI', 'MUCURI / ITAMARAJÚ',
       'ITAMARAJU / MUCURI', 'PEDRO  CANÁRIO', 'ITABATÃ / ARACRUZ',
       'SERRA  /ITABATÃ', 'VITÓRIA /NOVA VIÇOSA',
       'CONCEIÇÃO D BARRA/ITABATÃ', 'ITABATÃ/ GURIRI', 'PEDRO  CANARIO',
       'TEIXEIRA DE FREITAS/ TEIXEIRA DE FREITAS',
       'TEIXEIRA DE FREITAS/PRADO', 'PORTO SEGURO ',
       'TEIXEIRA DE FREITAS - AEROPORTO', 'FÁBRICA/ARACRUZ DESVIO',
       'SÃO JOSE DE ALCOBAÇA', 'VITÓRIA/MUCURI', 'VITÓRIA/ITABATÃ',
       'VITÓRIA/TEIXEIRA DE FREITAS DESVIO', 'SÃO MATEUS/POSTO DA MATA',
       'SÃO MATEUS/TEIXEIRA DE FREITAS', 'POSTO DA MATA/VITÓRIA DESVIO',
       'GURIRI/VITÓRIA DESVIO', 'ITABATÃ/VITÓRIA DESVIO',
       'TEIXEIRA DE FREITAS/VITÓRIA', 'ATENDIMENTO A DIRETORIA',
       'CONCEIÇAÕ DA BARRA', 'MUCURI/VITÓRIA DESVIO',
       'MUCURI/PORTO SEGURO', 'AERODROMO', 'VITÓRIA/SÃO MATEUS',
       'ITABATÃ/PORTO SEGURO', 'CARLOS CHAGAS/SÃO MATEUS',
       'FÁBRICA/CARLOS CHAGAS', 'FÁBRICA/CRISTAL', 'ITABATÃ/VITÓRIA',
       'VITÓRIA/PEDRO CANÁRIO', 'TEIXEIRA DE FREITAS/JUERANA',
       'TEIXEIRA DE FREITAS/ARACRUZ', 'ITABATÃ/GURIRI',
       'FÁBRICA/NOVA VENECIA', 'NOVA VENÉCIA/FÁBRICA',
       'ITABATÃ/P.CANARIO/TEIXEIRA DE FREITAS', 'FÁBRICA/CARAVELAS',
       'SERRA/TEIXEIRA DE FREITAS', 'PEDRO CANÁRIO/ITABATÃ', 'RIO MUCURI',
       'CONCEIÇÃO DA BARRA DESVIO', 'FÁBRICA/MONTANHA',
       'PEDRO CANÁRIO/BRAÇO DO RIO', 'CONCEIÇÃO DA BARRA/ VITÓRIA',
       "PEDRA D'AGUA", 'SÃO MATEUS/GURIRI', 'ITABATÃ/ARACRUZ DESVIO',
       'FÁBRICA/VITÓRIA', 'PORTO SEGURO/MUCURI', 'FÁBRICA/VITÓRIA DESVIO',
       'CONCEIÇÃO DA BARRA/ SÃO MATEUS', 'POUS.RIO MUC', 'NOVA VENÉCIA',
       'GOVERNADOR VALADARES', 'P.R. MUCURI', 'GUARAPARI', 'DIRETORIA',
       'COLATINA', 'ECO FLORESTA', 'FÁBRICA MUCURIC', 'HANGAR LÍDER',
       'SANTA TERESA', 'RANCHO ALGRE', 'TEXEIRA DE FREITAS', 'CMC'],
      dtype=object)

## ALTERAÇÕES NA COLUNA 'PASSAGEIRO'

In [20]:
df_combinado['TIPO'] = df_combinado['TIPO'].astype(str)
df_combinado['TIPO'] = df_combinado['TIPO'].str.upper()
df_combinado['TIPO'] = df_combinado['TIPO'].str.strip()

In [21]:
df_combinado['TIPO'].unique()

array(['CHAMADA', 'NAN', 'TAXI', 'VAN'], dtype=object)

In [22]:
df_combinado['TIPO'] = df_combinado['TIPO'].str.replace('nan', "Não Informado")

In [23]:
df_combinado['TIPO'].unique()

array(['CHAMADA', 'NAN', 'TAXI', 'VAN'], dtype=object)

In [25]:
df_combinado.to_excel(r'C:\Users\Markos Alves\Downloads\terceirizadas horiginal\terceirizadas.xlsx'.replace("\\","/"))